spring:
  datasource:
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${SECRET_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

      sql:
        init:
          mode: never

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}
